# cl <- makeCluster(detectCores(logical = F),"FORK")
# cl <- makeCluster(detectCores(logical = T),"FORK")
# cl <- makeCluster(detectCores(),"PSOCK")
cl <- makeCluster(rep("localhost",detectCores()))

clusterEvalQ(cl, library(rvest))
clusterEvalQ(cl, library(curl))
clusterEvalQ(cl, library(stringr))
clusterEvalQ(cl, library(shiny))
clusterEvalQ(cl, library(dplyr))
clusterEvalQ(cl, library(shinyjs))
clusterEvalQ(cl, library(data.table))
clusterEvalQ(cl, library(shinysky))
clusterEvalQ(cl, library(ggmap))
clusterEvalQ(cl, library(ggplot2))